#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AISpawnerData_DangerGrape

#include "Basic.hpp"

#include "BP_AISpawnerData_Phoebe_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AISpawnerData_DangerGrape.AISpawnerData_DangerGrape_C
// 0x0000 (0x00D0 - 0x00D0)
class UAISpawnerData_DangerGrape_C final  : public UBP_AISpawnerData_Phoebe_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AISpawnerData_DangerGrape_C">();
	}
	static class UAISpawnerData_DangerGrape_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAISpawnerData_DangerGrape_C>();
	}
};
static_assert(alignof(UAISpawnerData_DangerGrape_C) == 0x000008, "Wrong alinment on UAISpawnerData_DangerGrape_C");
static_assert(sizeof(UAISpawnerData_DangerGrape_C) == 0x0000D0, "Wrong size on UAISpawnerData_DangerGrape_C");

}

