#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimNotify_PlayFireFX

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AnimNotify_PlayFireFX.AnimNotify_PlayFireFX_C
// 0x0000 (0x0038 - 0x0038)
class UAnimNotify_PlayFireFX_C final  : public UAnimNotify
{
public:
	bool Received_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, class AActor* CallFunc_GetOwner_ReturnValue, class AFortPawn* K2Node_DynamicCast_AsFort_Pawn, bool K2Node_DynamicCast_bSuccess) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimNotify_PlayFireFX_C">();
	}
	static class UAnimNotify_PlayFireFX_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimNotify_PlayFireFX_C>();
	}
};
static_assert(alignof(UAnimNotify_PlayFireFX_C) == 0x000008, "Wrong alinment on UAnimNotify_PlayFireFX_C");
static_assert(sizeof(UAnimNotify_PlayFireFX_C) == 0x000038, "Wrong size on UAnimNotify_PlayFireFX_C");

}

