#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_BGA_Athena_CampFire_Trap

#include "Basic.hpp"

#include "B_BGA_Athena_CampFire_Trap_classes.hpp"
#include "B_BGA_Athena_CampFire_Trap_parameters.hpp"


namespace SDK
{

// Function B_BGA_Athena_CampFire_Trap.B_BGA_Athena_CampFire_Trap_C.ExecuteUbergraph_B_BGA_Athena_CampFire_Trap
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortBuildingInitializationReason       K2Node_Event_InitializationReason                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortBuildingPersistentState            K2Node_Event_BuildingPersistentState                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_BGA_Athena_CampFire_Trap_C::ExecuteUbergraph_B_BGA_Athena_CampFire_Trap(int32 EntryPoint, EFortBuildingInitializationReason K2Node_Event_InitializationReason, EFortBuildingPersistentState K2Node_Event_BuildingPersistentState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_BGA_Athena_CampFire_Trap_C", "ExecuteUbergraph_B_BGA_Athena_CampFire_Trap");

	Params::B_BGA_Athena_CampFire_Trap_C_ExecuteUbergraph_B_BGA_Athena_CampFire_Trap Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.K2Node_Event_InitializationReason = K2Node_Event_InitializationReason;
	Parms.K2Node_Event_BuildingPersistentState = K2Node_Event_BuildingPersistentState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_BGA_Athena_CampFire_Trap.B_BGA_Athena_CampFire_Trap_C.OnBuildingActorInitialized
// (BlueprintAuthorityOnly, Event, Public, BlueprintEvent)
// Parameters:
// EFortBuildingInitializationReason       InitializationReason                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortBuildingPersistentState            BuildingPersistentState                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_BGA_Athena_CampFire_Trap_C::OnBuildingActorInitialized(EFortBuildingInitializationReason InitializationReason, EFortBuildingPersistentState BuildingPersistentState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_BGA_Athena_CampFire_Trap_C", "OnBuildingActorInitialized");

	Params::B_BGA_Athena_CampFire_Trap_C_OnBuildingActorInitialized Parms{};

	Parms.InitializationReason = InitializationReason;
	Parms.BuildingPersistentState = BuildingPersistentState;

	UObject::ProcessEvent(Func, &Parms);
}

}

