#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Pistol_YEETknock

#include "Basic.hpp"

#include "B_Pistol_Flintlock_Athena_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Pistol_YEETknock.B_Pistol_YEETknock_C
// 0x0000 (0x12E0 - 0x12E0)
class AB_Pistol_YEETknock_C final  : public AB_Pistol_Flintlock_Athena_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Pistol_YEETknock_C">();
	}
	static class AB_Pistol_YEETknock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Pistol_YEETknock_C>();
	}
};
static_assert(alignof(AB_Pistol_YEETknock_C) == 0x000008, "Wrong alinment on AB_Pistol_YEETknock_C");
static_assert(sizeof(AB_Pistol_YEETknock_C) == 0x0012E0, "Wrong size on AB_Pistol_YEETknock_C");

}

