#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Athena_HolidayGiftBox

#include "Basic.hpp"

#include "B_Prj_Athena_HolidayGiftBox_classes.hpp"
#include "B_Prj_Athena_HolidayGiftBox_parameters.hpp"


namespace SDK
{

// Function B_Prj_Athena_HolidayGiftBox.B_Prj_Athena_HolidayGiftBox_C.ExecuteUbergraph_B_Prj_Athena_HolidayGiftBox
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class AActor*>                   K2Node_Event_HitActors                                 (ConstParm, ReferenceParm, HasGetValueTypeHash)
// TArray<struct FHitResult>               K2Node_Event_HitResults                                (ConstParm, ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)

void AB_Prj_Athena_HolidayGiftBox_C::ExecuteUbergraph_B_Prj_Athena_HolidayGiftBox(int32 EntryPoint, TArray<class AActor*>& K2Node_Event_HitActors, TArray<struct FHitResult>& K2Node_Event_HitResults)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_Athena_HolidayGiftBox_C", "ExecuteUbergraph_B_Prj_Athena_HolidayGiftBox");

	Params::B_Prj_Athena_HolidayGiftBox_C_ExecuteUbergraph_B_Prj_Athena_HolidayGiftBox Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.K2Node_Event_HitActors = std::move(K2Node_Event_HitActors);
	Parms.K2Node_Event_HitResults = std::move(K2Node_Event_HitResults);

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Prj_Athena_HolidayGiftBox.B_Prj_Athena_HolidayGiftBox_C.OnExploded
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// TArray<class AActor*>                   HitActors                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// TArray<struct FHitResult>               HitResults                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)

void AB_Prj_Athena_HolidayGiftBox_C::OnExploded(TArray<class AActor*>& HitActors, TArray<struct FHitResult>& HitResults)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_Athena_HolidayGiftBox_C", "OnExploded");

	Params::B_Prj_Athena_HolidayGiftBox_C_OnExploded Parms{};

	Parms.HitActors = std::move(HitActors);
	Parms.HitResults = std::move(HitResults);

	UObject::ProcessEvent(Func, &Parms);
}

}

