#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Ranged_GrenadeLauncher_Egg_Athena

#include "Basic.hpp"

#include "B_Prj_Ranged_GrenadeLauncher_Egg_Athena_classes.hpp"
#include "B_Prj_Ranged_GrenadeLauncher_Egg_Athena_parameters.hpp"


namespace SDK
{

// Function B_Prj_Ranged_GrenadeLauncher_Egg_Athena.B_Prj_Ranged_GrenadeLauncher_Egg_Athena_C.ExecuteUbergraph_B_Prj_Ranged_GrenadeLauncher_Egg_Athena
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       K2Node_Event_Hit                                       (ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AB_Prj_Ranged_GrenadeLauncher_Egg_Athena_C::ExecuteUbergraph_B_Prj_Ranged_GrenadeLauncher_Egg_Athena(int32 EntryPoint, struct FHitResult& K2Node_Event_Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_Ranged_GrenadeLauncher_Egg_Athena_C", "ExecuteUbergraph_B_Prj_Ranged_GrenadeLauncher_Egg_Athena");

	Params::B_Prj_Ranged_GrenadeLauncher_Egg_Athena_C_ExecuteUbergraph_B_Prj_Ranged_GrenadeLauncher_Egg_Athena Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.K2Node_Event_Hit = std::move(K2Node_Event_Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Prj_Ranged_GrenadeLauncher_Egg_Athena.B_Prj_Ranged_GrenadeLauncher_Egg_Athena_C.OnStop
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FHitResult                       Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AB_Prj_Ranged_GrenadeLauncher_Egg_Athena_C::OnStop(struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_Ranged_GrenadeLauncher_Egg_Athena_C", "OnStop");

	Params::B_Prj_Ranged_GrenadeLauncher_Egg_Athena_C_OnStop Parms{};

	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Prj_Ranged_GrenadeLauncher_Egg_Athena.B_Prj_Ranged_GrenadeLauncher_Egg_Athena_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_Prj_Ranged_GrenadeLauncher_Egg_Athena_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Prj_Ranged_GrenadeLauncher_Egg_Athena_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

