#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BGA_CurieFireMesh_MolotovCocktail_AdditionalMesh

#include "Basic.hpp"

#include "BGA_CurieFireMesh_MolotovCocktail_AdditionalMesh_classes.hpp"
#include "BGA_CurieFireMesh_MolotovCocktail_AdditionalMesh_parameters.hpp"


namespace SDK
{

// Function BGA_CurieFireMesh_MolotovCocktail_AdditionalMesh.BGA_CurieFireMesh_MolotovCocktail_AdditionalMesh_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   CallFunc_GetValueAtLevel_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_FTrunc_ReturnValue                            (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_CurieFireMesh_MolotovCocktail_AdditionalMesh_C::UserConstructionScript(float CallFunc_GetValueAtLevel_ReturnValue, int32 CallFunc_FTrunc_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_CurieFireMesh_MolotovCocktail_AdditionalMesh_C", "UserConstructionScript");

	Params::BGA_CurieFireMesh_MolotovCocktail_AdditionalMesh_C_UserConstructionScript Parms{};

	Parms.CallFunc_GetValueAtLevel_ReturnValue = CallFunc_GetValueAtLevel_ReturnValue;
	Parms.CallFunc_FTrunc_ReturnValue = CallFunc_FTrunc_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}

}

