#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CosmeticLoadoutScreen

#include "Basic.hpp"

#include "CosmeticLoadoutScreen_classes.hpp"
#include "CosmeticLoadoutScreen_parameters.hpp"


namespace SDK
{

// Function CosmeticLoadoutScreen.CosmeticLoadoutScreen_C.ExecuteUbergraph_CosmeticLoadoutScreen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESlateVisibility                        Temp_byte_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortCosmeticLoadoutScreenMode          Temp_byte_Variable_1                                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortCosmeticLoadoutScreenMode          Temp_byte_Variable_2                                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortCosmeticLoadoutScreenMode          Temp_byte_Variable_3                                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             Temp_text_Variable                                     ()
// class FText                             Temp_text_Variable_1                                   ()
// EFortLoadoutCardType                    K2Node_Event_CardType                                  (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UUMGSequencePlayer*               CallFunc_PlayAnimation_ReturnValue                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_ByteByte_ReturnValue               (ZeroConstructor, IsPlainOldData, NoDestructor)
// ESlateVisibility                        Temp_byte_Variable_4                                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortCosmeticLoadoutScreenMode          K2Node_Event_NewMode                                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             K2Node_Select_Default                                  ()
// class FText                             K2Node_Select_Default_1                                ()
// bool                                    Temp_bool_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor)
// ESlateVisibility                        K2Node_Select_Default_2                                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             K2Node_Select_Default_3                                (ConstParm)
// class USimpleFeatured_YellowButton_C*   K2Node_DynamicCast_AsSimple_Featured_Yellow_Button     (ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor)

void UCosmeticLoadoutScreen_C::ExecuteUbergraph_CosmeticLoadoutScreen(int32 EntryPoint, ESlateVisibility Temp_byte_Variable, EFortCosmeticLoadoutScreenMode Temp_byte_Variable_1, EFortCosmeticLoadoutScreenMode Temp_byte_Variable_2, EFortCosmeticLoadoutScreenMode Temp_byte_Variable_3, class FText Temp_text_Variable, class FText Temp_text_Variable_1, EFortLoadoutCardType K2Node_Event_CardType, class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, ESlateVisibility Temp_byte_Variable_4, EFortCosmeticLoadoutScreenMode K2Node_Event_NewMode, class FText K2Node_Select_Default, class FText K2Node_Select_Default_1, bool Temp_bool_Variable, ESlateVisibility K2Node_Select_Default_2, class FText K2Node_Select_Default_3, class USimpleFeatured_YellowButton_C* K2Node_DynamicCast_AsSimple_Featured_Yellow_Button, bool K2Node_DynamicCast_bSuccess)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CosmeticLoadoutScreen_C", "ExecuteUbergraph_CosmeticLoadoutScreen");

	Params::CosmeticLoadoutScreen_C_ExecuteUbergraph_CosmeticLoadoutScreen Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.Temp_byte_Variable = Temp_byte_Variable;
	Parms.Temp_byte_Variable_1 = Temp_byte_Variable_1;
	Parms.Temp_byte_Variable_2 = Temp_byte_Variable_2;
	Parms.Temp_byte_Variable_3 = Temp_byte_Variable_3;
	Parms.Temp_text_Variable = Temp_text_Variable;
	Parms.Temp_text_Variable_1 = Temp_text_Variable_1;
	Parms.K2Node_Event_CardType = K2Node_Event_CardType;
	Parms.CallFunc_PlayAnimation_ReturnValue = CallFunc_PlayAnimation_ReturnValue;
	Parms.CallFunc_EqualEqual_ByteByte_ReturnValue = CallFunc_EqualEqual_ByteByte_ReturnValue;
	Parms.Temp_byte_Variable_4 = Temp_byte_Variable_4;
	Parms.K2Node_Event_NewMode = K2Node_Event_NewMode;
	Parms.K2Node_Select_Default = K2Node_Select_Default;
	Parms.K2Node_Select_Default_1 = K2Node_Select_Default_1;
	Parms.Temp_bool_Variable = Temp_bool_Variable;
	Parms.K2Node_Select_Default_2 = K2Node_Select_Default_2;
	Parms.K2Node_Select_Default_3 = K2Node_Select_Default_3;
	Parms.K2Node_DynamicCast_AsSimple_Featured_Yellow_Button = K2Node_DynamicCast_AsSimple_Featured_Yellow_Button;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CosmeticLoadoutScreen.CosmeticLoadoutScreen_C.OnFlavorForScreenMode
// (Event, Protected, BlueprintEvent)
// Parameters:
// EFortCosmeticLoadoutScreenMode          NewMode                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCosmeticLoadoutScreen_C::OnFlavorForScreenMode(EFortCosmeticLoadoutScreenMode NewMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CosmeticLoadoutScreen_C", "OnFlavorForScreenMode");

	Params::CosmeticLoadoutScreen_C_OnFlavorForScreenMode Parms{};

	Parms.NewMode = NewMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CosmeticLoadoutScreen.CosmeticLoadoutScreen_C.OnPreviewTile
// (Event, Protected, BlueprintEvent)
// Parameters:
// EFortLoadoutCardType                    CardType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCosmeticLoadoutScreen_C::OnPreviewTile(EFortLoadoutCardType CardType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CosmeticLoadoutScreen_C", "OnPreviewTile");

	Params::CosmeticLoadoutScreen_C_OnPreviewTile Parms{};

	Parms.CardType = CardType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CosmeticLoadoutScreen.CosmeticLoadoutScreen_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UCosmeticLoadoutScreen_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CosmeticLoadoutScreen_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

