#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EmergencyNoticeWidgetBR

#include "Basic.hpp"

#include "EmergencyNoticeWidgetBR_classes.hpp"
#include "EmergencyNoticeWidgetBR_parameters.hpp"


namespace SDK
{

// Function EmergencyNoticeWidgetBR.EmergencyNoticeWidgetBR_C.Show Notice
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUMGSequencePlayer*               CallFunc_PlayAnimation_ReturnValue                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UEmergencyNoticeWidgetBR_C::Show_Notice(class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EmergencyNoticeWidgetBR_C", "Show Notice");

	Params::EmergencyNoticeWidgetBR_C_Show_Notice Parms{};

	Parms.CallFunc_PlayAnimation_ReturnValue = CallFunc_PlayAnimation_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EmergencyNoticeWidgetBR.EmergencyNoticeWidgetBR_C.ShowNotice
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             Title                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText                             Body                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UEmergencyNoticeWidgetBR_C::ShowNotice(class FText& Title, class FText& Body)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EmergencyNoticeWidgetBR_C", "ShowNotice");

	Params::EmergencyNoticeWidgetBR_C_ShowNotice Parms{};

	Parms.Title = Title;
	Parms.Body = Body;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EmergencyNoticeWidgetBR.EmergencyNoticeWidgetBR_C.HideNotice
// (Event, Protected, BlueprintEvent)

void UEmergencyNoticeWidgetBR_C::HideNotice()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EmergencyNoticeWidgetBR_C", "HideNotice");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EmergencyNoticeWidgetBR.EmergencyNoticeWidgetBR_C.ExecuteUbergraph_EmergencyNoticeWidgetBR
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             K2Node_Event_Title                                     (ConstParm)
// class FText                             K2Node_Event_Body                                      (ConstParm)
// class FText                             CallFunc_TextToUpper_ReturnValue                       ()

void UEmergencyNoticeWidgetBR_C::ExecuteUbergraph_EmergencyNoticeWidgetBR(int32 EntryPoint, class FText K2Node_Event_Title, class FText K2Node_Event_Body, class FText CallFunc_TextToUpper_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EmergencyNoticeWidgetBR_C", "ExecuteUbergraph_EmergencyNoticeWidgetBR");

	Params::EmergencyNoticeWidgetBR_C_ExecuteUbergraph_EmergencyNoticeWidgetBR Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.K2Node_Event_Title = K2Node_Event_Title;
	Parms.K2Node_Event_Body = K2Node_Event_Body;
	Parms.CallFunc_TextToUpper_ReturnValue = CallFunc_TextToUpper_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}

}

