#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InviteEventTitle

#include "Basic.hpp"

#include "InviteEventTitle_classes.hpp"
#include "InviteEventTitle_parameters.hpp"


namespace SDK
{

// Function InviteEventTitle.InviteEventTitle_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UInviteEventTitle_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InviteEventTitle_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InviteEventTitle.InviteEventTitle_C.ExecuteUbergraph_InviteEventTitle
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFortRuntimeOptions*              CallFunc_GetRuntimeOptions_ReturnValue                 (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsInviteUIDisabled_ReturnValue                (ZeroConstructor, IsPlainOldData, NoDestructor)

void UInviteEventTitle_C::ExecuteUbergraph_InviteEventTitle(int32 EntryPoint, class UFortRuntimeOptions* CallFunc_GetRuntimeOptions_ReturnValue, bool CallFunc_IsInviteUIDisabled_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InviteEventTitle_C", "ExecuteUbergraph_InviteEventTitle");

	Params::InviteEventTitle_C_ExecuteUbergraph_InviteEventTitle Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.CallFunc_GetRuntimeOptions_ReturnValue = CallFunc_GetRuntimeOptions_ReturnValue;
	Parms.CallFunc_IsInviteUIDisabled_ReturnValue = CallFunc_IsInviteUIDisabled_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}

}

