#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PhosphorusWipeoutRuntime

#include "Basic.hpp"

#include "PhosphorusWipeoutRuntime_classes.hpp"
#include "PhosphorusWipeoutRuntime_parameters.hpp"


namespace SDK
{

// Function PhosphorusWipeoutRuntime.FortAthenaMutator_PhosphorusWipeout.HandleBlockedCharacterMovement
// (Final, Native, Private, HasOutParams)
// Parameters:
// struct FHitResult                       InOutImpact                                            (Parm, OutParm, IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
// class AFortPawn*                        FortPawn                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_PhosphorusWipeout::HandleBlockedCharacterMovement(struct FHitResult* InOutImpact, class AFortPawn* FortPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_PhosphorusWipeout", "HandleBlockedCharacterMovement");

	Params::FortAthenaMutator_PhosphorusWipeout_HandleBlockedCharacterMovement Parms{};

	Parms.FortPawn = FortPawn;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (InOutImpact != nullptr)
		*InOutImpact = Parms.InOutImpact;
}


// Function PhosphorusWipeoutRuntime.FortAthenaMutator_PhosphorusWipeout.OnRep_KnockBackDataChanged
// (Final, Native, Public, HasOutParams)
// Parameters:
// TArray<struct FPhosphorusWipeoutKnockBackData>OldValue                                               (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_PhosphorusWipeout::OnRep_KnockBackDataChanged(TArray<struct FPhosphorusWipeoutKnockBackData>& OldValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_PhosphorusWipeout", "OnRep_KnockBackDataChanged");

	Params::FortAthenaMutator_PhosphorusWipeout_OnRep_KnockBackDataChanged Parms{};

	Parms.OldValue = std::move(OldValue);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhosphorusWipeoutRuntime.FortAthenaMutator_PhosphorusWipeout.SetPlayersShouldBreakThroughStructures
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bActive                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AFortPlayerPawn*                  PlayerPawn                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_PhosphorusWipeout::SetPlayersShouldBreakThroughStructures(bool bActive, class AFortPlayerPawn* PlayerPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_PhosphorusWipeout", "SetPlayersShouldBreakThroughStructures");

	Params::FortAthenaMutator_PhosphorusWipeout_SetPlayersShouldBreakThroughStructures Parms{};

	Parms.bActive = bActive;
	Parms.PlayerPawn = PlayerPawn;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhosphorusWipeoutRuntime.FortAthenaMutator_PhosphorusWipeout.GetKnockBackMultiplierInitialValue
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float AFortAthenaMutator_PhosphorusWipeout::GetKnockBackMultiplierInitialValue() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_PhosphorusWipeout", "GetKnockBackMultiplierInitialValue");

	Params::FortAthenaMutator_PhosphorusWipeout_GetKnockBackMultiplierInitialValue Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhosphorusWipeoutRuntime.FortAthenaMutator_PhosphorusWipeout.GetPercentDamageLowMaxThreshold
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float AFortAthenaMutator_PhosphorusWipeout::GetPercentDamageLowMaxThreshold() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_PhosphorusWipeout", "GetPercentDamageLowMaxThreshold");

	Params::FortAthenaMutator_PhosphorusWipeout_GetPercentDamageLowMaxThreshold Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhosphorusWipeoutRuntime.FortAthenaMutator_PhosphorusWipeout.GetPercentDamageMediumMaxThreshold
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float AFortAthenaMutator_PhosphorusWipeout::GetPercentDamageMediumMaxThreshold() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_PhosphorusWipeout", "GetPercentDamageMediumMaxThreshold");

	Params::FortAthenaMutator_PhosphorusWipeout_GetPercentDamageMediumMaxThreshold Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhosphorusWipeoutRuntime.FortAthenaMutator_ReroutePlayerEvent.FlushEventQueue
// (Final, Native, Private)

void AFortAthenaMutator_ReroutePlayerEvent::FlushEventQueue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_ReroutePlayerEvent", "FlushEventQueue");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhosphorusWipeoutRuntime.GA_Wipeout_PlayerKnockBackNative.MakeCachedMutator
// (Final, Native, Protected, BlueprintCallable, BlueprintPure)
// Parameters:
// class AFortAthenaMutator_PhosphorusWipeout*ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class AFortAthenaMutator_PhosphorusWipeout* UGA_Wipeout_PlayerKnockBackNative::MakeCachedMutator()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Wipeout_PlayerKnockBackNative", "MakeCachedMutator");

	Params::GA_Wipeout_PlayerKnockBackNative_MakeCachedMutator Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhosphorusWipeoutRuntime.GA_Wipeout_PlayerKnockBackNative.SaveKnockBackData
// (Final, Native, Protected, HasOutParams, BlueprintCallable)
// Parameters:
// struct FPhosphorusWipeoutKnockBackData  InKnockBackData                                        (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void UGA_Wipeout_PlayerKnockBackNative::SaveKnockBackData(struct FPhosphorusWipeoutKnockBackData& InKnockBackData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Wipeout_PlayerKnockBackNative", "SaveKnockBackData");

	Params::GA_Wipeout_PlayerKnockBackNative_SaveKnockBackData Parms{};

	Parms.InKnockBackData = std::move(InKnockBackData);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

