#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseFortnite_TeamStatValues

#include "Basic.hpp"

#include "VerseFortnite_StatContainer_classes.hpp"


namespace SDK
{

// SolarisGeneratedClass VerseFortnite_TeamStatValues.TeamStatValues
// 0x0058 (0x0090 - 0x0038)
class UTeamStatValues final  : public UStatContainer
{
public:
	uint8                                         Pad_7A6A[0x50];                                    // 0x0038(0x0050)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         __verse_0x28201082_team;                           // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7A6B[0x4];                                     // 0x008C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void _InitCDO();
	void _InitInstance();
	int32 GetPlayerStat(class UPlayerComponent* __verse_0x9F1D658F_player, int32 __verse_0x8C4546BB_statIndex);
	uint8 IncrementPlayerStat(class UPlayerComponent* __verse_0x9F1D658F_player, int32 __verse_0x8C4546BB_statIndex, int32 __verse_0x8461104C_increase);
	void SetPlayerStat(class UPlayerComponent* __verse_0x9F1D658F_player, int32 __verse_0x8C4546BB_statIndex, int32 __verse_0x00827935_newValue);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TeamStatValues">();
	}
	static class UTeamStatValues* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTeamStatValues>();
	}
};
static_assert(alignof(UTeamStatValues) == 0x000008, "Wrong alinment on UTeamStatValues");
static_assert(sizeof(UTeamStatValues) == 0x000090, "Wrong size on UTeamStatValues");
static_assert(offsetof(UTeamStatValues, __verse_0x28201082_team) == 0x000088, "Member 'UTeamStatValues::__verse_0x28201082_team' has a wrong offset!");

}

