#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Wumba_ItemCostComponent

#include "Basic.hpp"

#include "ItemCostComponent_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Wumba_ItemCostComponent.Wumba_ItemCostComponent_C
// 0x0000 (0x00B0 - 0x00B0)
class UWumba_ItemCostComponent_C final  : public UItemCostComponent_C
{
public:
	void GetCost(TMap<EFortResourceType, int32>* Cost, uint8 CallFunc_MakeLiteralByte_ReturnValue, uint8 CallFunc_MakeLiteralByte_ReturnValue_1, uint8 CallFunc_MakeLiteralByte_ReturnValue_2, class AActor* CallFunc_GetOwner_ReturnValue, class AB_Athena_Wumba_C* K2Node_DynamicCast_AsB_Athena_Wumba, bool K2Node_DynamicCast_bSuccess, const TMap<EFortResourceType, int32>& K2Node_MakeMap_Map);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Wumba_ItemCostComponent_C">();
	}
	static class UWumba_ItemCostComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWumba_ItemCostComponent_C>();
	}
};
static_assert(alignof(UWumba_ItemCostComponent_C) == 0x000008, "Wrong alinment on UWumba_ItemCostComponent_C");
static_assert(sizeof(UWumba_ItemCostComponent_C) == 0x0000B0, "Wrong size on UWumba_ItemCostComponent_C");

}

